### ISSUE TITLE
ASPNET 5.0: Reconnection tests failing 

### ISSUE THREAD

**Issue by mandrewcito** [mandrewcito/signalrcore#45]
**Describe the bug**
Test on reconnect fail with aspnet 5.0

======================================================================
FAIL: test_raw_reconnection (reconnection_test.TestReconnectMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/mandrewcito/signalrcore/test/reconnection_test.py", line 127, in test_raw_reconnection
    self.reconnect_test(connection)
  File "/mnt/d/mandrewcito/signalrcore/test/reconnection_test.py", line 106, in reconnect_test
    self.assertTrue(_lock.acquire(timeout=30))
AssertionError: False is not true

======================================================================
FAIL: test_reconnect_interval (reconnection_test.TestReconnectMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/d/mandrewcito/signalrcore/test/reconnection_test.py", line 58, in test_reconnect_interval
    self.reconnect_test(connection)
  File "/mnt/d/mandrewcito/signalrcore/test/reconnection_test.py", line 106, in reconnect_test
    self.assertTrue(_lock.acquire(timeout=30))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 55 tests in 184.478s

**Comment by mandrewcito** [comment]
Solved in #47
